### ISSUE TITLE
Sample accepts undefined trigger

### ISSUE THREAD

**Issue by Tauka** [zerobias/effector#210]
**Code to reproduce the issue:**
```
const $store = createStore(0);

const evSample = sample($store, undefined);
evSample.watch(v => console.log('sample triggered', v));
```

**Expected behavior:**
`sample` should throw error about undefined trigger

**Actual behavior:**
`sample` returns event, that gets immediately triggered

This behavior makes it extra hard to debug application, if somewhere for some reason undefined gets in sample instead of actual trigger

**Versions of packages used:**
20.2.1

**Comment by zerobias** [comment]
It is a valid use case, shorthand for `sample($store, $store)`, this is for batching store updates, like in `createStoreObject`

```js
const inc = createEvent()
const inc2 = inc.map(() => {})

const x = createStore(0)
  .on(inc, x => x + 1)
  .on(inc2, x => x + 1)

x.watch(n => {
  console.log('x watch %d', n)
})
sample(x).watch(n => {
  console.log('sample(x) watch %d', n)
})

inc()
```

```
x watch 0
sample(x) watch 0
x watch 1
x watch 2
sample(x) watch 2
```

https://share.effector.dev/gabu0f42

This is not a default behavior because its pretty rare to store to update by both original and computed events

[Motivation](https://github.com/zerobias/effector/issues/47)
